image: gitpod/workspace-full
checkoutLocation: gitpod-k3s
tasks:
  - name: prepare k3s
    command: |
      .gitpod/prepare-k3s.sh
  - name: kernel dev environment
    command: |
      .gitpod/qemu.sh
